///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AnalyticsDataModelResult {
/*
{
  "serviceBookings": 51,
  "promotionBookings": 1
}
*/

  int? serviceBookings;
  int? promotionBookings;
  double? totalAmountSpent;
  int? invites;

  AnalyticsDataModelResult({this.serviceBookings, this.promotionBookings, this.totalAmountSpent, this.invites});
  AnalyticsDataModelResult.fromJson(Map<String, dynamic> json) {
    serviceBookings = json['serviceBookings']?.toInt();
    promotionBookings = json['promotionBookings']?.toInt();
    totalAmountSpent = double.parse(json['totalAmountSpent'].toString());
    invites = json['totalInvites']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['serviceBookings'] = serviceBookings;
    data['promotionBookings'] = promotionBookings;
    data['totalAmountSpent'] = totalAmountSpent;
    data['totalInvites'] = invites;
    return data;
  }
}

class AnalyticsDataModel {
/*
{
  "status": "success",
  "message": "Operation Successfull",
  "result": {
    "serviceBookings": 51,
    "promotionBookings": 1
  }
}
*/

  String? status;
  String? message;
  AnalyticsDataModelResult? result;

  AnalyticsDataModel({
    this.status,
    this.message,
    this.result,
  });
  AnalyticsDataModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    result = (json['result'] != null) ? AnalyticsDataModelResult.fromJson(json['result']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (result != null) {
      data['result'] = result!.toJson();
    }
    return data;
  }
}
