import 'package:get/get.dart';

class LocaleLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_AE': {
          'Email': 'البريد الإلكتروني',
          'LOGIN': 'تسجيل الدخول',
          'Login': 'تسجيل الدخول',
          'Forgot Password?': 'هل نسيت كلمة السر؟',
          'Password': 'كلمه السر',
          'Or Login with': 'أو تسجيل الدخول باستخدام',
          'First Name': 'الاسم الاول',
          'Last Name': 'الكنية',
          'donot have': 'لا تملك حساب؟',
          'create one': 'اصنع واحدا',
          'Country': 'دولة',
          'Mobile Number': 'رقم الهاتف المحمول',
          'How did you here about us': 'كيف سمعت عنا',
          'Invitation Code': 'شفرة الدعوة',
          'REGISTER': 'تسجيل',
          'Already Have Account?': 'لديك حساب بالفعل؟',
          'welcome to outobucks': 'مرحبا بكم في otubucks',
          ' Hello ': 'مرحبًا',
          'One time password': 'كلمة السر لمرة واحدة',
          // ignore: prefer_adjacent_string_concatenation
          'enter_code': "الرجاء إدخال رمز التحقق الذي أرسلناه " +
              "\n" +
              "إلى عنوان بريدك الإلكتروني",
          'SUBMIT': 'إرسال',
          'Or': 'أو',
          'New Password': 'كلمة السر الجديدة',
          'Re-Enter Password': 'تأكيد كلمة المرور',
          'Enter Token': 'أدخل الرمز',
          'Home': 'مسكن',
          'My Profile': 'ملفي',
          'Booking History': 'سجل الحجز',
          'Purchase Product History': 'تاريخ شراء المنتج',
          'Notification': 'تنبيه',
          'Inbox': 'صندوق الوارد',
          'Transaction History': 'تاريخ المعاملات',
          'Analytics': 'تحليلات',
          'Wallet': 'محفظة',
          'Invite & earn': 'ادع واكسب',
          'Ratings': 'التقييمات',
          'Terms & Conditions': 'الأحكام والشروط',
          'About Us': 'معلومات عنا',
          'Estimation': 'تقدير',
          'Log Out': 'تسجيل خروج',
          'Search': 'بحث',
          'near me': 'بالقرب مني',
          'View Details': 'عرض التفاصيل',
          'View Profile': 'عرض الصفحة الشخصية',
          'Description': 'وصف',
          'Key Features': 'دلائل الميزات',
          'Service': 'خدمة',
          'Provider': 'مزود',
          'Service Price per hour': 'سعر الخدمة بالساعة',
          'Address': 'تبوك',
          'Date & Time': 'التاريخ والوقت',
          'Time': 'الوقت',
          'Upload image or Take a photo': 'قم بتحميل صورة أو التقط صورة',
          '(Up to 10 mb)': '(تصل إلى 10 ميغا بايت)',
          'Upload Video or Shoot a video': 'تحميل الفيديو أو تصوير الفيديو',
          'Leave voice note': 'اترك ملاحظة صوتية',
          'Leave Note (if any)': 'اترك ملاحظة (إن وجدت)',
          'Write a message...': 'اكتب رسالة...',
          'Adress': 'العنوان',
          'Request Estimation': 'طلب تقدير',
          'Thank you for booking. The vendor will get back to you shortly':
              'شكرا لك على الحجز. البائع سوف يقوم بالرد عليك قريبا',
          'Book Now': 'احجز الآن',
          'Pickup': 'يلتقط',
        },
        'en_US': {
          'Pickup': 'Pickup',
          'Book Now': 'Book Now',
          'Thank you for booking. The vendor will get back to you shortly':
              'Thank you for booking. The vendor will get back to you shortly',
          'Request Estimation': 'Request Estimation',
          'Adress': 'Adress',
          'Write a message...': 'Write a message...',
          'Leave Note (if any)': 'Leave Note (if any)',
          'Leave voice note': 'Leave voice note',
          'Upload Video or Shoot a video': 'Upload Video or Shoot a video',
          '(Up to 10 mb)': '(Up to 10 mb)',
          'Upload image or Take a photo': 'Upload image or Take a photo',
          'Time': 'Time',
          'Date & Time': 'Date & Time',
          'Address': 'Address',
          'Service Price per hour': 'Service Price per hour',
          'Provider': 'Provider',
          'Service': 'Service',
          'Key Features': 'Key Features',
          'Description': 'Description',
          'View Profile': 'View Profile',
          'Search': 'Search',
          'View Details': 'View Details',
          'near me': 'near me',
          'Home': 'Home',
          'Transaction History': 'Transaction History',
          'Analytics': 'Analytics',
          'Wallet': 'Wallet',
          'Invite & earn': 'Invite & earn',
          'Ratings': 'Ratings',
          'Terms & Conditions': 'Terms & Conditions',
          'About Us': 'About Us',
          'Email': 'Email',
          'Forgot Password?': 'Forgot Password?',
          'LOGIN': 'LOGIN',
          'Login': 'Login',
          'password': 'Password',
          'New Password': 'New Password',
          'Re-Enter Password': 'Re-Enter Password',
          'Or Login with': 'Or Login With',
          'donot have': 'Don’t have an account?',
          'create one': 'create one',
          'First Name': 'First Name',
          'Last Name': 'Last Name',
          'Country': 'Country',
          'Mobile Number': 'Mobile Number',
          'How did you here about us': 'How did you here about us',
          'Invitation Code': 'Invitation Code',
          'REGISTER': 'REGISTER',
          'Already Have Account?': 'Already Have Account?',
          'welcome to outobucks': 'welcome to outobucks',
          ' Hello ': ' Hello ',
          'One time password': 'ONE TIME PASSWORD',
          // ignore: prefer_adjacent_string_concatenation
          'enter_code': "Please Enter The Verification Code We Sent" +
              "\n" +
              "to your email address",
          'SUBMIT': 'SUBMIT',
          'Or': 'Or',
          'Enter Token': 'Enter Token',
          'My Profile': 'My Profile',
          'Booking History': 'Booking History',
          'Purchase Product History': 'Purchase Product History',
          'Notification': 'Notification',
          'Inbox': 'Inbox',
          'Estimation': 'Estimation',
          'Log Out': "Log Out"
        },
      };
}
