import 'package:get/get.dart';

class LocaleLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_AE': {
          'Email': 'البريد الإلكتروني',
          'LOGIN': 'تسجيل الدخول',
          'Login': 'تسجيل الدخول',
          'Forgot Password?': 'هل نسيت كلمة السر؟',
          'Password': 'كلمه السر',
          'Or Login with': 'أو تسجيل الدخول باستخدام',
          'First Name': 'الاسم الاول',
          'Last Name': 'الكنية',
          'donot have': 'لا تملك حساب؟',
          'create one': 'اصنع واحدا',
          'Customer Support': 'دعم العملاء',
          'Country': 'دولة',
          'Mobile Number': 'رقم الهاتف المحمول',
          'How did you here about us': 'كيف سمعت عنا',
          'Invitation Code': 'شفرة الدعوة',
          'REGISTER': 'تسجيل',
          'Already Have Account?': 'لديك حساب بالفعل؟',
          'welcome to outobucks': 'مرحبا بكم في otubucks',
          ' Hello ': 'مرحبًا',
          'One time password': 'كلمة السر لمرة واحدة',
          // ignore: prefer_adjacent_string_concatenation
          'enter_code': "الرجاء إدخال رمز التحقق الذي أرسلناه " +
              "\n" +
              "إلى عنوان بريدك الإلكتروني",
          'SUBMIT': 'إرسال',
          'Or': 'أو',
          'Car': 'سيارة',
          'OPEN': 'يفتح',
          'Cart': 'عربة التسوق',
          'Profile': 'حساب تعريفي',
          'New Password': 'كلمة السر الجديدة',
          'Re-Enter Password': 'تأكيد كلمة المرور',
          'Enter Token': 'أدخل الرمز',
          'Home': 'مسكن',
          'My Profile': 'ملفي',
          'Booking History': 'سجل الحجز',
          'Purchase Product History': 'تاريخ شراء المنتج',
          'Notification': 'تنبيه',
          'Inbox': 'صندوق الوارد',
          'Transaction History': 'تاريخ المعاملات',
          'Analytics': 'تحليلات',
          'Wallet': 'محفظة',
          'Invite & earn': 'ادع واكسب',
          'Ratings': 'التقييمات',
          'Terms & Conditions': 'الأحكام والشروط',
          'About Us': 'معلومات عنا',
          'Estimation': 'تقدير',
          'Log Out': 'تسجيل خروج',
          'Search': 'بحث',
          'near me': 'بالقرب مني',
          'View Details': 'عرض التفاصيل',
          'View Profile': 'عرض الصفحة الشخصية',
          'Description': 'وصف',
          'Submit': 'يُقدِّم',
          'Your FeedBack': 'تعليقاتك',
          'How was your experience': 'كيف كانت تجربتك',
          'Cancel': 'يلغي',
          'Sub Total Amount ': 'المبلغ الاجمالي',
          'Decline': 'انخفاض',
          'Pay 50%': 'ادفع 50٪',
          'Offer Already Created': 'عرض تم إنشاؤه بالفعل',
          'Make Offer': 'تقديم عرض',
          'Service Tax ( 5 %)': 'ضريبة الخدمة (5٪)',
          'Key Features': 'دلائل الميزات',
          'Service': 'خدمة',
          'Card Holder': 'حامل البطاقة',
          'Provider': 'مزود',
          'Expires': 'تنتهي',
          'GO BACK HOME': 'ارجع الى البيت',
          'Service Price per hour': 'سعر الخدمة بالساعة',
          'Address': 'تبوك',
          'My Booking': 'الحجز',
          'Date & Time': 'التاريخ والوقت',
          'Time': 'الوقت',
          'Upload image or Take a photo': 'قم بتحميل صورة أو التقط صورة',
          '(Up to 10 mb)': '(تصل إلى 10 ميغا بايت)',
          'Upload Video or Shoot a video': 'تحميل الفيديو أو تصوير الفيديو',
          'Leave voice note': 'اترك ملاحظة صوتية',
          'Leave Note (if any)': 'اترك ملاحظة (إن وجدت)',
          'Write a message...': 'اكتب رسالة...',
          'Adress': 'العنوان',
          'Thank you for booking.': 'شكرا لك على الحجز.',
          'The vendor will get back to you soon.': 'البائع سوف يقوم بالرد عليك قريبا',
          'Request Estimation': 'طلب تقدير',
          'Thank you for booking. The vendor will get back to you shortly':
              'شكرا لك على الحجز. البائع سوف يقوم بالرد عليك قريبا',
          'Book Now': 'احجز الآن',
          'Pickup': 'يلتقط',
          'Code': 'شفرة',
          'City': 'مدينة',
          'Name': 'اسم',
          'KM': 'كم',
          'Car model year': 'سنة طراز السيارة',
          'Number': 'رقم',
          'Save': 'يحفظ',
          'Update': 'تحديث',
          'Car Plate Number': 'رقم لوحة سيارة',
          'Color': 'لون',
          'Choose Your Car': 'اختر سيارتك',
          'Update Your Profile': 'تحديث ملفك الشخصي',
          'Add \n Emirates id back': 'إضافة هوية الإمارات مرة أخرى',
          'Add \n Emirates id front': 'إضافة واجهة هوية الإمارات',
          'Add \n Driving Licence': 'إضافة رخصة قيادة',
          'Add \n Mulkia': 'أضف مُلكيّة',
          'Enter your car details': 'أدخل تفاصيل سيارتك',
          'Add Emergency Contact Details': 'أضف تفاصيل الاتصال في حالات الطوارئ',
          'Car brand': 'ماركة السيارة',
          'PickCar model year': 'سنة طراز السيارة',
          'Add Car': 'أضف سيارة',
          'Auto Repair services': 'خدمات تصليح السيارات',
          'Categories': 'التصنيفات',
          'Verify': 'يؤكد',
          'Edit Number': 'تحرير الرقم',
          'Sub Categories': 'الفئات الفرعية',
          'Cancelled': 'ألغيت',
          'CHECKOUT': 'الدفع',
          'Promotions': 'الترقيات',
          'Proceed to pay': 'المضي قدما في الدفع',
          'Balance Amount ': 'مقدار وسطي',
          '50 % Payed Amount': '50٪ المبلغ المدفوع',
          'Total Amount ': 'المبلغ الإجمالي',
          'CVV Check': 'فحص CVV',
          'Payment Detail': 'تفاصيل الدفع',
          'Expiry Date': 'تاريخ الانتهاء',
          'Card Holder Name': 'إسم صاحب البطاقة',
          'Credit Card Number': 'رقم بطاقة الائتمان',
          'ADD NEW CARD': 'أضف بطاقة جديدة',
          'Completed': 'مكتمل',
          'In Progress': 'في تَقَدم',
          'Pending': 'قيد الانتظار',
          'AED': 'درهم إماراتي',
          'Search by title': 'البحث عن طريق العنوان',
          'Search by date': 'البحث بالتاريخ',
          'Service Title: ': "عنوان الخدمة:",
          'Booking Date : ': "تاريخ الحجز:",
          "Price :  ":"سعر :  ",
          "Paid  : ":"مدفوع  :",
          'View Booking': "عرض الحجز",
          'Requested': "مطلوب",
          'Accepted': "وافقت",
          'Declined': "انخفض",
          "No data found":"لاتوجد بيانات",
          "Balance Payment":"ميزان المدفوعات",
          'View Estimation': "عرض التقدير",
          'Offering Amount': "عرض التقدير",
          'RATED': 'مصنفة',
          'Booked': 'حجز',
          'Total': 'تخفيض',
          'Amount': 'مقدار',
          'Price': 'سعر',
          'Title': 'لقب',
          'Qty': 'الكمية',
          'Sub Total': 'المجموع الفرعي',
          'Discount': 'تخفيض',
          'Thanks for Connecting with us': 'شكرا لاكمالك معنا',
          'Invoice Date:  ': 'رقم الفاتورة:',
          'Invoice Number :': 'اسم الزبون:',
          'Customer name:  ': 'اسم الزبون:',
          'Download Invoice': 'تحميل فاتورة',
          'Customer Estimation': 'تقدير العميل',
          'Tax Invoice': 'فاتورة ضريبية',
          're-book': 'إعادة الكتاب',
          'Booking Cancelled': 'تم إلغاء الحجز',
          'Fully Paid': 'مدفوعة بالكامل',
          'Give rating': 'إعطاء التقييم',
          'Reschedule': 'إعادة الجدولة',
        },
        'en_US': {
          'Offering Amount': 'Offering Amount',
          'Categories': 'Categories',
          'Cancelled': 'Cancelled',
          'Completed': 'Completed',
          'In Progress': 'In Progress',
          'Pending': 'Pending',
          'Paid  : ': 'Paid  : ',
          'AED': 'AED',
          'Car': 'Car',
          'Reschedule': 'Reschedule',
          're-book': 're-book',
          'Booking Cancelled': 'Booking Cancelled',
          'Fully Paid': 'Fully Paid',
          "Balance Payment": "Balance Payment",
          'Sub Categories': 'Sub Categories',
          'Search by title': 'Search by title',
          'Search by date': 'Search by date',
          'Service Title: ': "Service Title: ",
          'Booking Date': "Booking Date",
          'Price :  ': "Price :  ",
          'View Booking': "View Booking",
          'Requested': "Requested",
          'Accepted': "Accepted",
          'Declined': "Declined",
          'Submit': "Submit",
          'View Estimation': "View Estimation",
          'Pickup': 'Pickup',
          'Auto Repair Services': 'Auto Repair Services',
          'Book Now': 'Book Now',
          'Thank you for booking. The vendor will get back to you shortly':
              'Thank you for booking. The vendor will get back to you shortly',
          'Request Estimation': 'Request Estimation',
          'Adress': 'Adress',
          'Write a message...': 'Write a message...',
          'Leave Note (if any)': 'Leave Note (if any)',
          'Leave voice note': 'Leave voice note',
          'Upload Video or Shoot a video': 'Upload Video or Shoot a video',
          '(Up to 10 mb)': '(Up to 10 mb)',
          'Upload image or Take a photo': 'Upload image or Take a photo',
          'Time': 'Time',
          'Date & Time': 'Date & Time',
          'Customer Support': 'Customer Support',
          'Address': 'Address',
          'Service Price per hour': 'Service Price per hour',
          'Provider': 'Provider',
          'Service': 'Service',
          'Key Features': 'Key Features',
          'Description': 'Description',
          'View Profile': 'View Profile',
          'Search': 'Search',
          'View Details': 'View Details',
          'near me': 'near me',
          'Home': 'Home',
          'Transaction History': 'Transaction History',
          'Analytics': 'Analytics',
          'Wallet': 'Wallet',
          'Invite & earn': 'Invite & earn',
          'Ratings': 'Ratings',
          'Terms & Conditions': 'Terms & Conditions',
          'About Us': 'About Us',
          'Email': 'Email',
          'Forgot Password?': 'Forgot Password?',
          'LOGIN': 'LOGIN',
          'My Booking': 'My Booking',
          'Login': 'Login',
          'password': 'Password',
          'New Password': 'New Password',
          'Re-Enter Password': 'Re-Enter Password',
          'Or Login with': 'Or Login With',
          'donot have': 'Don’t have an account?',
          'create one': 'create one',
          'First Name': 'First Name',
          'Last Name': 'Last Name',
          'Country': 'Country',
          'Mobile Number': 'Mobile Number',
          'How did you here about us': 'How did you here about us',
          'Invitation Code': 'Invitation Code',
          'REGISTER': 'REGISTER',
          'Already Have Account?': 'Already Have Account?',
          'welcome to outobucks': 'welcome to outobucks',
          ' Hello ': ' Hello ',
          'One time password': 'ONE TIME PASSWORD',
          // ignore: prefer_adjacent_string_concatenation
          'enter_code': "Please Enter The Verification Code We Sent" +
              "\n" +
              "to your email address",
          'SUBMIT': 'SUBMIT',
          'Or': 'Or',
          'Enter Token': 'Enter Token',
          'My Profile': 'My Profile',
          'Booking History': 'Booking History',
          'Purchase Product History': 'Purchase Product History',
          'Notification': 'Notification',
          'Inbox': 'Inbox',
          'Estimation': 'Estimation',
          'RATED': 'RATED',
          'Booked': 'Booked',
          'Give rating': 'Give rating',
          'Log Out': "Log Out"
        },
      };
}
